config/routes.rb
Rails.application.routes.draw do

  post '/like/likenew' => "like#likenew" ,as:'like_new'
  #get '/comments/:id/createcomments' => "comments#createcomments" ,as:'comment_new'
  resources :comments
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :post

  root "post#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  belongs_to :parent, polymorphic: true

  has_many :comments, as: :parent
  has_many :likes, as: :parent
end

app/models/like.rb
class Like < ApplicationRecord

	belongs_to :user
		belongs_to :parent , polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
belongs_to :user
has_many :comments, as: :parent
has_many :likes , as: :parent
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :comments
has_many :posts
has_many :likes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
		if (params[:comment][:parent_type] == 'post')
			@parent = Post.find(params[:comment][:parent_id])
		else
			@parent = Comment.find(params[:comment][:parent_id])
		end

		@comment = Comment.create(
				content: params[:comment][:content],
				user_id: current_user.id,
				parent: @parent
			)
      @like=Like.new
      redirect_to post_index_path
    end


      def edit
        @comment=Comment.find(params[:id])
      end

      def update
        @comment=Comment.find(params[:id])
        @comment.update(
          content: params[:comment][:content],
          user_id: current_user.id
        )
        redirect_to post_index_path
      end

      def destroy
        @comment=Comment.find(params[:id]).destroy
        redirect_to post_index_path
      end
	end

app/controllers/like_controller.rb
class LikeController < ApplicationController

  def likenew
    #@like.save
  #  @likecount=Like.where(post_id: params[:id]).length
    #@like = Like.create(user_id: current_user.id, post_id: params[:id])
    #@likecount=Like.where(user_id: current_user.id).length
#  @likecount=@likecount+1
if (params[:like][:parent_type] == 'post')
  #@parent mai like ke parent ki puri details aa rahi hai
  @parent = Post.find(params[:like][:parent_id])
else
  @parent = Comment.find(params[:like][:parent_id])
end
    if Like.exists?(parent: @parent , user_id: current_user.id)
      a=Like.where(parent: @parent , user_id: current_user.id)
      a[0].destroy
      # @likecount=@likecount-1
    else

    @like = Like.create(parent: @parent , user_id: current_user.id)
end
  #@like = Like.create(user_id: current_user.id, post_id: params[:id])
    #redirect_to post_index_path,(id: post_id)
    #redirect_to :action => action_name,:id => 3
  #  redirect_to like_path(passed_parameter: params[:like][:id])
  redirect_to post_index_path
  end

#   def likecount
#     @post_id=params[:passed_parameter]
#     @likecount=Like.where(post_id:@post_id).length
#     @likecount=@likecount+1
#     redirect_to post_index
# # return RedirectToAction("index", "post");
# # RedirectToAction("action name", "controller name");
#   end
end

app/controllers/post_controller.rb
class PostController < ApplicationController

  def index
    @post=Post.new
    @Allpost=Post.all
    @comment=Comment.new
    @like=Like.new
    @user=User.all
    #@postlike=Post.find(params[:id])
    #@likecount=Like.where(post_id: @postlike).length
  end

  def create
    Post.create(
      content: params[:post][:content],
      user_id: current_user.id
    )
    redirect_to action:'index'
  end

  def edit
    @post=Post.find(params[:id])
  end

  def update
    @post=Post.find(params[:id])
    @post.update(
      content: params[:post][:content],
      user_id: current_user.id
    )
    redirect_to action:'index'
  end

  def destroy
    @post=Post.find(params[:id]).destroy
    redirect_to action:'index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/comments/_comment.html.erb
<li>
	<p class="comment-content"><%= comment.content %></p>
	<p class="comment-user">
		<small>
			By <%= comment.user.email %> at <%= comment.created_at.to_date %>
		</small>
	</p>
<div style="display: inline-block;">
		<%= form_for @like, :url => {:controller => "like", :action => "likenew"} do |l|%>
					<input type="hidden" name="like[parent_type]" value="comment">
					<input type="hidden" name="like[parent_id]" value="<%= comment.id %>">
					<%= l.submit 'like' %>
		<%end%>
</div>
<div id="div-like"><%=comment.likes.length%></div>
<div class="post-div">
 <%= link_to "edit",edit_comment_path(:id => comment)%>
 <%= link_to 'Delete',comment_path(:id =>comment), method: :delete%>
</div>
</li>

	 <%= form_for @comment,:url => {:controller => "comments", :action => "create"} do |c| %>
		 <input type="hidden" name="comment[parent_type]" value="comment">
		 <input type="hidden" name="comment[parent_id]" value="<%= comment.id %>">
		 <%= c.label :content, "reply" %>
		 <%= c.text_field :content %>
		 <%= c.submit "submit" %>
	 <%end%>


	<ul>
			  <% comment.comments.reverse.each do |fc| %>
			 	<%= render 'comments/show', comment: fc %>
				<div class="post-div">
					<%= link_to "edit",edit_comment_path(:id => fc.id)%>
					<%= link_to 'Delete',comment_path(:id =>fc.id), method: :delete%>
				</div>
		 	 	<% end %>
	</ul>

app/views/comments/_show.html.erb
<li>
	<p class="comment-content"><%= comment.content %></p>
	<p class="comment-user">
		<small>
			By <%= comment.user.email %> at <%= comment.created_at.to_date %>
		</small>
	</p>
</li>

<div style="display: inline-block;">
		<%= form_for @like, :url => {:controller => "like", :action => "likenew"} do |l|%>
					<input type="hidden" name="like[parent_type]" value="comment">
					<input type="hidden" name="like[parent_id]" value="<%= comment.id %>">
					<%= l.submit 'like' %>
		<%end%>
</div>


<div id="div-like"><%=comment.likes.length%></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header id="body-header">
        <div class="logo">
          <p>Socialchemy</p>
        </div>
        <nav>
          <ul>
            <%if user_signed_in?%>
            <li>
              <%= current_user.email %>
            </li>
            <li>
              <%= link_to "sign out",destroy_user_session_path , method: :delete %>
            </li>
            <%else%>
            <li>
              <%= link_to "join",new_user_registration_path %>
            </li>
            <li>
              <%= link_to "sign in", new_user_session_path %>
            </li>
            <%end%>
          </ul>
        </nav>
      </header>
    <%= yield %>
  </body>
</html>

app/views/post/_form.html.erb
<%= form_for post,:url => {:controller => "post", :action => actionname} do |f| %>
<%= f.label :content %>:
<%= f.text_field :content %>
<%=f.submit%>
<%end%>

app/views/post/_formcomments.html.erb
<h5>Comments</h5>
   <%= form_for @comment,:url => {:controller => "comments", :action => "create"} do |comment| %>
     <input type="hidden" name="comment[parent_type]" value="post">
     <input type="hidden" name="comment[parent_id]" value="<%= p.id %>">
     <%= comment.label :content, "New Comment" %>
     <%= comment.text_field :content %>
     <%= comment.submit %>
   <%end%>

   <ul>
       <% p.comments.reverse.each do |comment| %>
         <%= render 'comments/comment', comment: comment %>
       <% end %>
   </ul>

app/views/post/_showpost.html.erb
<%=p.content%>
<small>
  By <%= p.user.email %>
  at <%= p.created_at.to_date %>
</small>

  <div style="display: inline-block;">
			<%= form_for @like, :url => {:controller => "like", :action => "likenew"} do |l|%>
	    			<input type="hidden" name="like[parent_type]" value="post">
	    			<input type="hidden" name="like[parent_id]" value="<%= p.id %>">
	    			<%= l.submit 'like' %>
			<%end%>
	</div>

app/views/post/edit.html.erb
<div id="edit-posts-style">
  <%= render "post/form" ,post: @post, actionname:'update'%>
  <%=link_to "back",post_path%>
</div>

app/views/post/index.html.erb
<main class="body-main">
  <%if user_signed_in? %>
  <h3>Posts</h3>
  <br>

  <%= render "post/form" ,post: @post, actionname:'index'%>

<div id="page-look" style="display: inline-flex;width: 100vw;justify-content: space-between;">

  <div id="left-look" style="display: inline-flex;width: 100vw;justify-content: space-between;background-color: grey;">
    <ul>
      
  </div>
  <div id="center-bar" style="width: 205%;  height: 100%;">
            <ul style=" list-style: none;margin: 0px;padding: 0px;">
                <%@Allpost.reverse.each do |post| %>
                  <li id="post<%=post.id%>" class="post-li">
                    <%=render "post/showpost" , p:post%>
                    <div class="post-div">
                      <!-- <%= link_to 'like',like_new_path() %> -->
                      <!-- <div id="div-like"><%=post.likes.length%></div> -->
                      <div id="div-like"><%=post.likes.length%></div>
                      <%= link_to "edit",edit_post_path(:id => post.id)%>
                      <%= link_to 'Delete',post_path(:id =>post.id), method: :delete%>
                    </div>
                    <div class="comments-div">
                    <%=render "post/formcomments" , p:post%>
                    </div>
                  </li>
                <%end%>
            </ul>
    </div>
    <div id="right-look" style="display: inline-flex;width: 100vw;justify-content: space-between;background-color: grey;"></div>
  </div>
  <%end%>
</main>